# list

In [1]:
## initialize
x = [0, 1, 2]
x = [i for i in range(3)]

In [2]:
## append element
x.append(10)
print(x)
## append list
print(x + [4,5,6])
print(x) #immutable x!!!
x.extend([4,5,6])# change x its own. same x[len(x):] = [4,5,6]
print(x)

[0, 1, 2, 10]
[0, 1, 2, 10, 4, 5, 6]
[0, 1, 2, 10]
[0, 1, 2, 10, 4, 5, 6]


In [3]:
## remove and pop
x.remove(10) #remove the element 10
print(x)
x.pop(3) #remove the 3th element
print(x)

[0, 1, 2, 4, 5, 6]
[0, 1, 2, 5, 6]


In [4]:
## insert an element
x.insert(1, 100) #insert 1th place
print(x)

[0, 100, 1, 2, 5, 6]


In [5]:
## first and last
print(x[0])
print(x[-1])

0
6


In [6]:
## in and index
print(5 in x) #True/False
print(x.index(100)) #Return index or error

True
1


In [7]:
## inner expression
print([i for i in range(5) if i != 3])
print([[i*j for i in range(3)] for j in range(3)])
print([i*j for i in range(3) for j in range(3)])

[0, 1, 2, 4]
[[0, 0, 0], [0, 1, 2], [0, 2, 4]]
[0, 0, 0, 0, 1, 2, 0, 2, 4]


# Standard Input and Output

In [8]:
## stdin (raw_input function in ver2.x)
a = int(input())
## split with space
b, c = map(int, input().split())
## split with comma
d, e = map(int, input().split(','))
print(a+b+c+d+e)

123
1 2
1,2
129


# Datetime

In [9]:
import datetime
now = datetime.datetime.now()
print(now.strftime("%Y/%m/%d/%H%M%S"))

2016/12/12/191113


# numpy

In [10]:
import numpy as np

In [11]:
x = [True, False, True]
y = np.array(x)
print(y)

[ True False  True]


In [12]:
# Reverse bit
~y

array([False,  True, False], dtype=bool)

## linear algebra

In [13]:
# Define Matrix
x = np.array([[2,2], [2,4]])
# Matrix Product
np.dot(x, x)

array([[ 8, 12],
       [12, 20]])

In [14]:
# Eigen value
la, v = np.linalg.eig(x)
# Eigen vector v is orthogonal becahse x is symetric
print(np.dot(v, v.transpose()))
print('----------------------------------------------')
# Reconstruct original matrix
print(np.dot(np.dot(v, np.diag(la)), v.transpose()))

[[ 1.  0.]
 [ 0.  1.]]
----------------------------------------------
[[ 2.  2.]
 [ 2.  4.]]
