In [1]:
import numpy as np
import scipy.sparse
import scipy.sparse.linalg

In [2]:
#We should create sparse matrix as lil_matrix at first
x = scipy.sparse.lil_matrix((14, 4))
x[0, 0] = 1.2
x[1, 0] = 3.2
x[7, 1] = 6.9
x[0, 2] = 3.8
x[9, 2] = 5.7
print(x)

  (0, 0)	1.2
  (0, 2)	3.8
  (1, 0)	3.2
  (7, 1)	6.9
  (9, 2)	5.7


In [3]:
#Convert to dense matrix
print(x.todense())

[[ 1.2  0.   3.8  0. ]
 [ 3.2  0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   6.9  0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   5.7  0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


In [4]:
#singular value decomposition for sparse matrix(should be converted to csr or csc before that)
svds = scipy.sparse.linalg.svds(x.tocsr(), k=3)
svds

(array([[ -2.13306519e-01,   5.68870059e-01,   1.45906061e-16],
        [ -9.52809640e-01,   5.86112527e-02,   1.51166165e-17],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   2.56574085e-16,  -1.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  2.15995644e-01,   8.20336259e-01,   2.10355995e-16],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]]),
 array([ 3.33161596,  6.89277412,  6.9       ]),
 array([[ -9.91998690e-01,   0.00000000e+00,   1.2624

In [5]:
#Reproduce matrix by svd result
np.dot(np.dot(svds[0], np.diag(svds[1])), svds[2])

array([[  1.20000000e+00,  -1.75458256e-18,   3.80000000e+00,
         -2.77531555e-16],
       [  3.20000000e+00,  -7.58780362e-19,   6.66133815e-16,
          6.60005105e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [ -1.63612015e-18,   6.90000000e+00,  -2.66928302e-18,
         -1.96343743e-31],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  1.33226763e-15,  -2.20505989e-18,   5.70000000e+00,
         -7.87550203e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e