In [25]:
import numpy as np
import scipy.sparse
import scipy.sparse.linalg

In [7]:
#We should create sparse matrix as lil_matrix at first
x = scipy.sparse.lil_matrix((14, 4))
x[0, 0] = 1.2
x[1, 0] = 3.2
x[7, 1] = 6.9
x[0, 2] = 3.8
x[9, 2] = 5.7
print(x)

<14x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in LInked List format>

In [8]:
#Convert to dense matrix
print(x.todense())

[[ 1.2  0.   3.8  0. ]
 [ 3.2  0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   6.9  0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   5.7  0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]


In [27]:
#singular value decomposition for sparse matrix(should be converted to csr or csc before that)
svds = scipy.sparse.linalg.svds(x.tocsr(), k=3)
svds

(array([[ -2.13306519e-01,   5.68870059e-01,  -5.15388031e-15],
        [ -9.52809640e-01,   5.86112527e-02,  -4.88550239e-16],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  4.59869262e-16,   8.89109521e-15,   1.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  2.15995644e-01,   8.20336259e-01,  -7.45601096e-15],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00]]),
 array([ 3.33161596,  6.89277412,  6.9       ]),
 array([[ -9.91998690e-01,   2.22044605e-16,   1.2624

In [28]:
#Reproduce matrix by svd result
np.dot(np.dot(svds[0], np.diag(svds[1])), svds[2])

array([[  1.20000000e+00,  -8.93271129e-16,   3.80000000e+00,
          3.36012275e-16],
       [  3.20000000e+00,  -4.87665469e-16,  -6.10622664e-16,
          5.51069276e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [ -1.05152867e-15,   6.90000000e+00,  -1.28993063e-15,
          7.66053887e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [ -1.22124533e-15,  -1.06559487e-15,   5.70000000e+00,
          1.94041945e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e